name: release
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '42 11 * * 4'

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    strategy:
      matrix:
        arch:
          - aarch64
        platform:
          - linux/arm64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Run
        run: |
          BRANCH="master"
          if [ "${GITHUB_REF_TYPE}" = "tag" ] ; then
            BRANCH="${GITHUB_REF_NAME}"
          fi
          ./build.sh ${BRANCH}
          mv nvim-${BRANCH}.appimage nvim-${BRANCH}-${{ matrix.arch }}.appimage
      -
        name: Release for tags
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            nvim-${GITHUB_REF_NAME}-${{ matrix.arch }}.appimage
      -
        name: Release for master
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          name: master
          prerelease: true
          files: |
            nvim-master-${{ matrix.arch }}.appimage
